# Generated by Django 5.1.7 on 2025-03-27 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_remove_interaction_type_interaction_comment_text_and_more'),
        ('subscriptions', '0002_alter_subscription_artist'),
        ('users', '0003_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='users.artist'),
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
