# Generated by Django 5.1.7 on 2025-04-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_track_artist_delete_artist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='listeninghistory',
            options={'ordering': ['-listened_at']},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='trackfeature',
            options={'ordering': ['track']},
        ),
        migrations.AlterModelOptions(
            name='trackstatistics',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='interaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_type',
            field=models.CharField(choices=[('like', 'Like'), ('stream', 'Stream'), ('comment', 'Comment')], db_index=True, default='stream', max_length=10),
        ),
        migrations.AlterField(
            model_name='listeninghistory',
            name='listened_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='track',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='trackfeature',
            name='mood',
            field=models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('energetic', 'Energetic'), ('calm', 'Calm'), ('romantic', 'Romantic'), ('angry', 'Angry'), ('chill', 'Chill')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='trackstatistics',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
