# Generated by Django 5.1.7 on 2025-03-27 21:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_track_artist_delete_artist'),
        ('playlists', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playlist',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='playlisttrack',
            unique_together={('playlist', 'track')},
        ),
    ]
