# Generated by Django 5.1.7 on 2025-04-17 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_interaction_options_and_more'),
        ('playlists', '0003_alter_playlist_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='playlisttrack',
            options={'ordering': ['-added_at']},
        ),
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['-added_at']},
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='user',
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(choices=[('most_liked', 'Most Liked'), ('admin_picks', 'Admin Picks'), ('for_you', 'For You'), ('liked_songs', 'Liked Songs')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='playlisttrack',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='playlisttrack',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_tracks', to='playlists.playlist'),
        ),
        migrations.AlterField(
            model_name='playlisttrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_playlists', to='music.track'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='music.track'),
        ),
    ]
