# Generated by Django 5.1.7 on 2025-03-18 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=10)),
                ('max_upload_rate', models.IntegerField(default=4)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('end_subscription', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='active', max_length=10)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='music.artist')),
            ],
        ),
    ]
