# Generated by Django 5.1.7 on 2025-04-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionplan_remove_subscription_type_and_more'),
        ('users', '0004_alter_user_options_alter_follow_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status'], name='subscriptio_status_5e8870_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['end_subscription'], name='subscriptio_end_sub_b3e028_idx'),
        ),
    ]
